---
- name: Ensure base_dir exists
  ansible.builtin.file:
      state: directory
      path: "{{ base_dir }}/prysm"
      mode: "0755"
  tags:
      - prysm.install

- name: Download prysm file
  ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/prysmaticlabs/prysm/master/prysm.sh
      dest: "{{ base_dir }}/prysm/prysm.sh"
  tags:
      - prysm.install

- name: Render start_node.sh file
  ansible.builtin.template:
    src: start_node.sh.j2
    dest: "{{ base_dir }}/prysm/start_node.sh"
    owner: root
    group: root
    mode: 0755
  tags:
      - prysm.install

- name: Copy jwt.hex
  ansible.builtin.copy:
    src: jwt.hex
    dest: "{{ base_dir }}/prysm/.jwt.hex"
    mode: "0644"
  tags:
      - prysm.install

- name: Render prysm.service file
  ansible.builtin.template:
    src: prysm.service.j2
    dest: /etc/systemd/system/prysm.service
    mode: 0644
    owner: root
    group: root
  tags:
      - prysm.install

- name: Restart prysm
  ansible.builtin.systemd:
    name: prysm.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  tags:
      - prysm.install