# Base role configuration variables
# Go language configuration
go_pkg: https://go.dev/dl/go1.23.1.linux-amd64.tar.gz
go_check_sum: sha256:49bbb517cfa9eee677e1e7897f7cf9cfdbcf49e05f61984a2789136de359f9bd

# Default disk device - override this in playbook or inventory
# IMPORTANT: Change this to match your actual disk device
dev: /dev/xxx  # Placeholder - must be updated for your environment