---
- name: Ensure base_dir exists
  ansible.builtin.file:
      state: directory
      path: "{{ base_dir }}/geth"
      mode: "0755"
  tags:
      - geth.install

- name: Ensure tmp_dir exists
  ansible.builtin.file:
      state: directory
      path: "{{ base_dir }}/geth/tmp"
      mode: "0755"
  tags:
      - geth.install

- name: Download go-ethereum tools pkg
  ansible.builtin.get_url:
      url: "{{ geth }}"
      dest: /tmp/geth.tgz
      checksum: "{{ geth_check_sum }}"
  tags:
      - geth.install

- name: Unarchive
  ansible.builtin.unarchive:
      src: /tmp/geth.tgz
      dest: "{{ base_dir }}/geth/tmp"
      remote_src: yes
      extra_opts: [--strip-components=1]
  tags:
      - geth.install

- name: Rename the extracted directory
  ansible.builtin.shell: mv "{{ base_dir }}/geth/tmp" "{{ base_dir }}/geth/geth-{{ version }}"
  tags:
      - geth.install

- name: Render start_node.sh file
  ansible.builtin.template:
    src: start_node.sh.j2
    dest: "{{ base_dir }}/geth/start_node.sh"
    owner: root
    group: root
    mode: 0755
  tags:
      - geth.install

- name: Copy jwt.hex
  ansible.builtin.copy:
    src: jwt.hex
    dest: "{{ base_dir }}/geth/.jwt.hex"
    mode: "0644"
  tags:
      - geth.install

- name: Render geth.service file
  ansible.builtin.template:
    src: geth.service.j2
    dest: /etc/systemd/system/geth.service
    mode: 0644
    owner: root
    group: root
  tags:
      - geth.install

- name: Restart geth
  ansible.builtin.systemd:
    name: geth.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  tags:
      - geth.install